{{- range .Values.externalSecrets.secretNames }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ . | lower | replace "/" "-" }}
  annotations:
    {{- toYaml $.Values.externalSecrets.annotations | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.externalSecrets.clusterSecretStore }}
  target:
    name: {{ . | lower | replace "/" "-" }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ . }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
