apiVersion: v2
name: karpenter-resources
description: A Helm chart for Karpenter Custom Resources
maintainers:
  - name: DAI
    email: dai@tamedia.ch
type: application
version: 1.0.1
appVersion: "1.6.0"
