{{- include "generic.validateValues" . -}}
{{- if .Values.deploymentEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ include "generic.namespace" . }}
  labels:
    {{- include "generic.labels" (dict "context" . "labels" .Values.workloadLabels) | nindent 4 }}
  {{- if or .Values.workloadAnnotations .Values.commonAnnotations }}
  annotations:
    {{- include "generic.annotations" (dict "context" . "annotations" .Values.workloadAnnotations) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas | default 1 }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic.podTemplate" . | nindent 4 }}
{{- end }}
{{- range $name, $deployment := .Values.extraDeployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" $ }}-{{ $name }}
  namespace: {{ include "generic.namespace" $ }}
  labels:
    {{- $extraLabels := merge (dict "app.kubernetes.io/component" $name) ($deployment.labels | default dict) }}
    {{- include "generic.labels" (dict "context" $ "labels" $extraLabels) | nindent 4 }}
  {{- if or $deployment.annotations $.Values.commonAnnotations }}
  annotations:
    {{- include "generic.annotations" (dict "context" $ "annotations" $deployment.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- if not $deployment.hpa }}
  replicas: {{ $deployment.replicas | default 1 }}
  {{- end }}
  {{- with $deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with $deployment.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with $deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  {{- with $deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic.podTemplate" (dict "root" $ "config" $deployment "componentName" $name) | nindent 4 }}
{{- end }}
