{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- if and .Values.auth.username (ne .Values.auth.username "postgres") }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
